---

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: ~/kubeadm-ansible/roles/metallb/files/checking.sh 
    owner: root
    group: root
    mode: '0777'
- name : execute a shell script
  script: ~/kubeadm-ansible/roles/metallb/files/checking.sh 
  register: abc
- debug:
    msg: "{{ abc.stdout_lines }}"


- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: metallb


- name: "Create configmap file"
  template:
    src: metallb-layer-2-config.yml.j2
    dest: "{{ tmp_dir }}/metallb-layer-2-config.yml"
  tags: metallb

- name: "Create MetalLB configmap in kubernetes"
  shell: "kubectl apply -f {{ tmp_dir }}/metallb-layer-2-config.yml"
  tags: metallb

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: metallb
